### ISSUE TITLE
Refactor memory management

### ISSUE THREAD

**Issue by muellerberndt** [muellerberndt/micro-gpt#28]
The current memory code is pretty ad-hoc and unoptimized. It's unclear whether the query method and values used lead to optimal results in long-running tasks. Some questions:

- Is it better to summarize memory during storage or during retrieval (at the moment we use a mix of both)?
- Can the [query](https://github.com/muellerberndt/micro-gpt/blob/de27634021378a489b20c7d9254691e3cdc700e4/microgpt.py#L89) be improved?
- Is [5 items](https://github.com/muellerberndt/micro-gpt/blob/de27634021378a489b20c7d9254691e3cdc700e4/memory.py#L82) a sensible number?
- What are the optimal settings for `MAX_CONTEXT_SIZE` and `MEMORY_ITEM_SIZE` for GPT-3.5 and GPT-4?
- Are there other ways to improve the memory system?

Ideally, several variants and tweaks should be debugged & tested on long-running tasks that require lots of memory, such as summarizing multiple websites or similar.

**Comment by ibrarzahoor** [comment]
Here are some suggestions for improving the memory system:

Summarization: It is generally better to summarize during storage rather than retrieval. Summarizing during storage compresses the information, making retrieval more efficient. Summarizing during retrieval requires accessing the full, uncompressed data, which is less efficient. I would recommend summarizing aggressively during storage.

Query improvements: Some ways to improve the query method include:

Using semantic similarities, not just exact string matches. This could retrieve relevant memories even when the query is not an exact match.
Ranking memories by relevance to the query, not just retrieving the top 5. This would give the model more flexibility in how many memories to retrieve.
Allowing "fuzzy" queries that don't exactly match any single memory but could be synthesized from multiple relevant memories.
Memory size: 5 items may be too small for tasks requiring a large memory. I would experiment with larger memory sizes, e.g. 10-50 items, to see the impact on long-running tasks. For GPT-3.5 and GPT-4, MAX_CONTEXT_SIZE = 5000 and MEMORY_ITEM_SIZE = 400 seems like a good starting point, but this could be tuned for optimal performance.

Other optimizations:

Implement a "forgetting" mechanism that removes less relevant or important memories over time. This prevents the memory from growing too large and "catastrophic forgetting".
Add memory metadata, like timestamps, semantic tags, etc. This could aid in queries, relevance ranking, and forgetting.
Compress the memory contents using an algorithm like GZIP to minimize memory footprint.
Experiment with different memory architectures, e.g. a hierarchical memory with multiple "levels" of increasing abstraction.
To properly tune and test these options, running experiments on long, memory-intensive tasks and evaluating metrics like accuracy, memory usage, and compute time would be necessary. Significant gains could likely be achieved by optimizing for the specific use cases and data the model deals with.

**Comment by Koalamanx** [comment]
I have been trying to get Micro-GPT working for 2 days. I cant sign up for Pinecone as is doesnt take sign ups atm. 
I can install Chromeadb as it crashes whilst installing on my Raspi 4. 

Kind of bummed. What can I do?

**Comment by dev-hacki** [comment]
1. Is it better to summarize memory during storage or during retrieval (at the moment we use a mix of both)?
It depends on the specific use case and requirements. Summarizing memory during storage can save time during retrieval, but it may also result in loss of important details. Summarizing during retrieval can provide more context and details, but it may take longer to retrieve the information.

2. Can the query be improved?
Yes, the query can be improved by optimizing the search algorithm and using relevant keywords for better results.

3. Is 5 items a sensible number?
It depends on the context and specific use case. Five items may be sufficient for some tasks, while others may require more or less.

4. What are the optimal settings for MAX_CONTEXT_SIZE and MEMORY_ITEM_SIZE for GPT-3.5 and GPT-4?
The optimal settings for MAX_CONTEXT_SIZE and MEMORY_ITEM_SIZE depend on the specific use case and requirements. It is recommended to experiment with different settings and evaluate their performance.

5. Are there other ways to improve the memory system?
Yes, there are other ways to improve the memory system, such as implementing more advanced data structures, using machine learning algorithms for better organization and retrieval, and optimizing storage and access methods.

**Comment by ismaelc** [comment]
From what I observed:
- Pulling the last X results  ([sliding window](https://github.com/ismaelc/micro-gpt/blob/add-sliding-window-chromadb/memory.py#L206)) - works great for objectives that require sequential actions like writing code projects into a folder
- Summarization - Didn't do that many tests here, but I imagine this is useful when results are being pulled from sources that require a big context window e.g. web results, reading lengthy files, etc.

**Comment by ismaelc** [comment]
> I have been trying to get Micro-GPT working for 2 days. I cant sign up for Pinecone as is doesnt take sign ups atm. I can install Chromeadb as it crashes whilst installing on my Raspi 4.
> 
> Kind of bummed. What can I do?

Can you create an issue so we can track. Also paste the error you're getting when installing chromadb

**Comment by muellerberndt** [comment]
I found a good prompt for testing the memory implementation:

```
python microgpt.py "Come up with an original idea for an online job that you can do autonomously. It is important that you can do this job with minimal support by the user. You must handle sourcing of clients, communication with clients, and payment by yourself. Proceed to find clients and perform the job. If you no need any support, such as creating an account, ask the user to help. All payments should go to the Paypal account [paypay account]."
```

This reliably triggers long-running tasks with many steps (and with pretty interesting results 🙂).

**Comment by muellerberndt** [comment]
Hey everyone, I just created a Telegram group for coordinating development. If you like to join, drop me a DM on [Twitter](https://twitter.com/muellerberndt) for the link.
